# Generated by Django 5.1.5 on 2025-01-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='table_header_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
