# Generated by Django 5.1.5 on 2025-01-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournment',
            name='tournment_type',
            field=models.CharField(choices=[('LBSB', 'LBSB'), ('SQUADCUP', 'Squad Cup'), ('TREINO_CLAS', 'Treino Classificatório')], max_length=20),
        ),
        migrations.DeleteModel(
            name='TournmentType',
        ),
    ]
