# Generated by Django 5.1.5 on 2025-01-26 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournment', '0002_alter_tournment_tournment_type_delete_tournmenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournment',
            name='pointsFormat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournment.pointsformat'),
        ),
        migrations.AlterField(
            model_name='tournment',
            name='tournment_type',
            field=models.CharField(choices=[('LBSB', 'LBSB'), ('SQUADCUP', 'Squad Cup'), ('TREINO_CLAS', '5x5 de clãs')], max_length=20),
        ),
    ]
