# Generated by Django 5.1.5 on 2025-01-26 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournment', '0003_tournment_pointsformat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playermatch',
            name='date',
        ),
        migrations.AlterField(
            model_name='tournment',
            name='clan1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clan1_tournaments', to='tournment.clan'),
        ),
        migrations.AlterField(
            model_name='tournment',
            name='clan2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clan2_tournaments', to='tournment.clan'),
        ),
    ]
