# Generated by Django 5.1.5 on 2025-01-26 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournment', '0005_tournment_isfinished'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermatch',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pointsformat',
            name='lost_points_per_death',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(0)]),
        ),
    ]
