# Generated by Django 5.1.5 on 2025-02-03 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unity', models.CharField(blank=True, max_length=50, null=True)),
                ('order_type', models.CharField(choices=[('biggest', 'Maior'), ('lowest', 'Menor')], default='biggest', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
                ('record_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.recordtype')),
            ],
        ),
    ]
